version: "3.4"
services:
       front-end-app:
        container_name: frontend
        image: frontend-test
        restart: always
        ports:
          - "5080:80"
          - "5443:443"
        links:
          - backend-app
       backend-app:
           container_name: back-end
           image: ghcr.io/deanparrish/portfoliositebackend:master   
           restart: always
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             restart: always
             volumes:
               - mongodata:/data/db
volumes:
    mongodata:
      external: true              
