name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
    
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "auth_config.json"
        json: ${{ secrets.ConfigureAuth }}
        dir: '/src'
        
    - name: Build Docker Image    
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
